### ISSUE TITLE
Ramp prefab is missing 

### ISSUE THREAD

**Issue by SungbinChoi** [beyretb/AnimalAI-Environment#1]
I have built Animal AI env binary from this project's source code, and did some experiment with it.
I found that 'Ramp' object is always not built. 
On Unity editor,  'RampFBX (Missing Prefab)' is shown missing when I opened 'AnimalAI-Environment/Assets/AnimalAIOlympics/TrainEnv/Prefab/Immovable/Ramp.prefab' file.
Could you please fix it?

**Comment by beyretb** [comment]
Thank you for pointing out the missing link, I've fixed it.
I also converted the tunnels blender files to fbx (to remove the dependence on blender). Let me know if this creates any issue on your side.
